name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Version
        id: version
        run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      # Only update version if needed (e.g., for consistency), but no push
      - name: Update Version in Script
        run: |
          if [ -f "commodebian.sh" ]; then
            sed -i "s/^VERSION=.*/VERSION=${{ env.VERSION }}/" commodebian.sh
          else
            echo "commodebian.sh not found, skipping version update"
          fi

      - name: Create Release Package
        run: |
          mkdir -p release
          zip -r release/commodebian-${{ env.VERSION }}.zip . -x "*.git*"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Commodebian ${{ github.ref_name }}"
          body: |
            Release version ${{ github.ref_name }}.
            - Includes updated scripts and resources.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/commodebian-${{ env.VERSION }}.zip
          asset_name: commodebian-${{ env.VERSION }}.zip
          asset_content_type: application/zip